# Generated by Django 6.1 on 2026-09-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
    ]
